name: example
description: Example.
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  built_value: ^7.0.9
  dfunc: ^0.3.2

dev_dependencies:
  built_value_generator: ^7.0.9
  build_runner: ^1.0.0
  dfunc_builder: ^0.0.3
  pedantic: ^1.7.0
  test: ^1.6.0
