name: dfunc
description: Functional batteries for Dart. Implementation of Either, Optional etc.
version: 0.4.7
homepage: https://github.com/ookami-kb/dfunc

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  quiver: '>=2.0.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
