name: dfunc
description: Functional batteries for Dart. Implementation of Either, Optional etc.
version: 0.5.1
homepage: https://github.com/ookami-kb/dfunc

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
